# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: orden-service-secret
  namespace: orden-service
  labels:
    app: orden-service

type: Opaque

# stringData convierte automáticamente a base64
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
